### ISSUE TITLE
Link zu ADVs / DPAs ergänzen (data-processing-agreements)

### ISSUE THREAD

**Issue by madiko** [alexplusde/dsgvo#14]
Hallo Alex,

heute wurde ich von Joschi Kuphal von Tollwerk angesprochen. Sie arbeiten gerade an einer Übersicht mit diversen DPAs. Lass uns das auch verlinken. Ich übernehme das, sobald ich von Joschi das "Go" habe (sie sind auch noch Work-in-Progress). 

Hier schon mal der Link für Dich: 
https://github.com/tollwerk/data-processing-agreements

Würdest Du dieses Issue bitte mir zuordnen? Ich habe noch nicht so ganz verstanden, wie ich das selbst machen kann. Danke.

Viele Grüße,
Franziska

**Comment by alexplusde** [comment]
Einfach hier reinposten. In Slack geht es für mich unter. Und gerne kannst du direkt einen PR für die README.md machen - diese wird dann in der Hilfe angezeigt.

**Comment by alexplusde** [comment]
Wie schaut es da von deiner Seite aus @madiko ?

**Comment by madiko** [comment]
Hallo Alex,

das wäre für mich eher was im Doku-PlugIn. Ich sah, dass ich da noch nichts sah ;-)
Sprich: Das Doku-PlugIn hast Du noch nicht aufgenommen. ¯\_(ツ)_/¯

Dort würde ich es unter FAQ bzw. Weiterführende Informationen packen.

Ich schlage zudem vor, dass Du die READ.me im Doku-PlugIn aufteilst (die Seite ist recht lang). Gib Bescheid, wenn ich darin unterstützen soll. Ich hab ja jetzt (endlich) Übung im Doku-PlugIn bauen.

Viele Grüße,
Franziska

**Comment by alexplusde** [comment]
Nein, dafür braucht es kein Doku-Plug-in. So umfangreich ist es nicht. Die README.md reicht dafür vollkommen aus und wird, genauso wie das Doku-Plugin, als Reiter im Addon angezeigt.

Bevor jedoch kein Material da ist, lohnt eine Diskussion ja auch nicht.
