### ISSUE TITLE
Verzögerung des gesamten Seitenaufbaus

### ISSUE THREAD

**Issue by maxsmily** [alexplusde/dsgvo#31]
Wenn bei mir die aktuelle Entwicklungs-Version 0.2.1 installiert ist, verzögern sich alle HTTP-Requests um ca. 1 - 1.5 Sekunden. Zum Beispiel benötigt ein beliebiges Media-Manager-Bild bei aktiviertem DSGVO-Addon ca. 1.7 Sekunden zum Laden (davon 1.55 Warten) und bei deaktiviertem Addon nur 0.2 Sekunden (davon 0.07s Warten). Ähnliche Verzögerung auch im Backend. Da ist irgendwas resourcen-fressend eingebunden...

**Comment by alexplusde** [comment]
Das kann ich in der Praxis im Moment nicht nachstellen, habe das bei ein paar anderen Seiten installiert und eingebunden.

**Comment by alexplusde** [comment]
@maxsmily gerade gesehen, das ist dein erstes Issue. Bist du denn auch im Slack-Channel? Kann auf jeden Fall das von dir beschriebene Verhalten nicht nachstellen. Vielleicht können wir uns ja dort mal kurz unterhalten.

Welche REDAXO-Version setzt du ein? Hast du davor noch ein Core-Update gemacht o.ä.? Welcher Hoster / Servertyp?

**Comment by maxsmily** [comment]
Hallo Alex, ich hab mir dein Addon nun genauer angesehen und nach verdächtigen Programmteilen gesucht. Das Addon ist ja sehr aufgeräumt, so konnte ich durch einfaches Deaktivieren einzelner Blöcke Testmessungen vornehmen. Die Problemstelle ist die Tabellen-Prüfung in der boot.php. Wenn ich die einfach auskommentiere und mein Beispiel-Media-Manager-Bild im Browser aufrufe, macht das einen Lade-Unterschied von fast 1 Sekunde. Ist es denn nötig, die Tabelle bei jedem Aufruf neu zu prüfen? Reicht das nicht beim Installieren? Grüße Daniel

**Comment by alexplusde** [comment]
Das war ein Überbleibsel aus der Entwicklung, ich habe es eigentlich schon raus genommen. Seltsam, dass es bei dir zu solchen Verzögerungen geführt hat. Danke fürs nachforschen... Wird bei der Veröffentlichung korrigiert sein.
