### ISSUE TITLE
Paginierung bei Texten im Server funktioniert nicht richtig 

### ISSUE THREAD

**Issue by Pixeldaniel** [alexplusde/dsgvo#32]
Beim Seitenwechsel müssen werte für domain und func mitgegeben werden

**Comment by alexplusde** [comment]
Vorübergehend die Anzahl der Datensätze in der Darstellung auf 100 erhöhen ;)

**Comment by Pixeldaniel** [comment]
ist auf 100 erhöht ;)

**Comment by joachimdoerr** [comment]
af37b2511d9861e5d230ce1940e9502f670a4b55
020503249c1c279c3c90ec8d7aeb2ee14eaed427

**Comment by joachimdoerr** [comment]
56e86543d3959443c36d662fd0e11e31cba21413

**Comment by alexplusde** [comment]
Wird in R5.6.1 gelöst sein und ist schon mal angepasst.
